/**
 * Issues
 * - the list will have two, the same items: Accordion: app/components/ui/accordion.tsx
 *   - i guess that's because the file name sort of conflict with the exported name 'Accordion'?
 * - Not sure how to display the logging
 * - If download the uploaded mapper file as a local file, that file will not have any type declaration
 *
 * Facts
 * - When design change the component property (eg., add, remove, rename, ...)
 *   - we need to unpublish the relevant mappers in code, and run the mapping logic again, and then republish
 * - The file content will be generated with AI assistence, so it's just not just apure static analysis
 *   > cuz it in reality, the actual mapping logic can be complex (eg., this file)
 * - During the mapping generation, it's important that the provided code components have strong and complete type declaration
 *   > cuz that'll help to increase the accuracy of the generated code
 * - Make sure to do named export for the components, cuz that's how Builder devtool can find them out and do the mapping
 * - although Builder said that they don't save our code in any way, but that's not true,
 *   - cuz when I close all the builder sites, and close the dev server
 *   - and when I open "Design System" tab the Figma layer that has some mapped components, I can see that Builder still know that which components have been mapped
 */
import {
  figmaMapping,
  type BaseFigmaProps,
  type ChildrenNode,
} from "@builder.io/dev-tools/figma";
import {
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "~/src/components/primitive/accordion";

// It seems it can't show the Nest Instances even we have enabled that in Figma
// But maybe it's fine, cuz in this case the only nest instance is the `figma.Content`
/**
 * The key is literally just the same as the defined property name in Figma.
 * Currently, there're only 4 cases of properties that can be used below:
 * - Text
 * - Boolean
 * - Variant
 * - Instance Swap
 *
 * For "Nested Instances", it's not applicable here;
 * cuz those instances either can be auto-generated by Builder,
 * or should be mapped by another mapper files.
 */
interface FigmaComponentProps extends BaseFigmaProps {
  Content: ChildrenNode; // Swap instance
  "Trigger Text"?: string; // Text Property
  Active?: "Off" | "On"; // A variant; if it's true and false on Figma, then it'd be expressed as `'true' |'false'`
  State?: "Default" | "Hover"; // A variant
}

figmaMapping({
  componentKey: "1830998013f9970f2e39e901f33f391d4b32fa2f",
  mapper(figma: FigmaComponentProps) { // it's called "Mapper"
    return (
      <AccordionItem value='item-1'>
        <AccordionTrigger>{figma["Trigger Text"]}</AccordionTrigger>
        <AccordionContent>{figma.Content}</AccordionContent>
      </AccordionItem>
    );
  },
});
