import { Heading, HeadingSubtitle, HeadingTitle } from "#/components/ui/Heading/Heading.tsx";
import { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from "#/components/ui/InputOtp/InputOtp.tsx";
import { useState } from "react";

export default () => {
  const [value, setValue] = useState('')
  return (
    <div className="tw:flex tw:flex-col tw:items-center tw:gap-2 tw:w-[320px]">
      <Heading size="h4" className="tw:text-center">
        <HeadingTitle>Enter Code</HeadingTitle>
        <HeadingSubtitle>Enter the 6-digit code generated by Google Authenticator</HeadingSubtitle>
      </Heading>
      <InputOTP maxLength={6} value={value} onChange={setValue}>
        <InputOTPGroup>
          <InputOTPSlot index={0} />
          <InputOTPSlot index={1} />
          <InputOTPSlot index={2} />
        </InputOTPGroup>
        <InputOTPSeparator />
        <InputOTPGroup>
          <InputOTPSlot index={3} />
          <InputOTPSlot index={4} />
          <InputOTPSlot index={5} />
        </InputOTPGroup>
      </InputOTP>
    </div>
  )
}
